# Generated by Django 4.2.7 on 2023-11-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_sale_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('Red', 'Urgent'), ('Blue', 'General'), ('Green', 'Success')], max_length=10)),
                ('notification_msg', models.CharField(max_length=280)),
                ('is_notification', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-modified_at']},
        ),
    ]
