# Generated by Django 4.2.7 on 2023-11-11 14:35

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_is_notification_notification_is_notified'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='notification',
            managers=[
                ('notified', django.db.models.manager.Manager()),
            ],
        ),
    ]
