# Generated by Django 4.2.7 on 2023-11-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_notification_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='notification',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('red', 'Urgent'), ('blue', 'General'), ('green', 'Success')], max_length=10),
        ),
    ]
