# Generated by Django 4.2.7 on 2023-11-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_notification_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='notification',
            managers=[
            ],
        ),
    ]
