# Generated by Django 4.2.7 on 2023-11-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_sale_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
